### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by dpc** [andreyorst/fzf.kak#25] opened 2018-11-23 05:51 UTC
## Problem description

When doing file search, preview just doesn't work:

```
fish: Illegal command name “(highlight --failsafe -O ansi 'Cargo.lock' || cat 'Cargo.lock')
highlight --failsafe -O ansi 'Cargo.lock' || cat 'Cargo.lock') 2>/dev/null | head -n 100
```

I'm at 

```
commit 1bcee973ab0285649df52fe200cd84575c4d20aa (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Andrey Orst <andreyorst@gmail.com>
Date:   Fri Nov 16 18:37:34 2018 +0300

    Revert "search for tag file in every previous directory until reach home"

    This reverts commit 850139e30e11dcad807c1d8de47a8803851c6224.
```

and Kakoune v2018.10.27.

**Comment by andreyorst** [comment] 2018-11-23 06:04
How did `Cargo.lock` got into this command? There should be a `{}`. Could you try with bash? I think that fish does the expansion of `{}` in this line.

**Comment by andreyorst** [comment] 2018-11-23 06:06
Also please provide all info from the bug report template. Are you're using x11 or tmux? What's your OS and shell versions? All those things help me investigate and reproduce the issue.

**Comment by dpc** [comment] 2018-11-23 06:37
`Cargo.lock` was the current select entry in the `fzf` file list.

Ha. I just tried and this happens only when I'm using `tmux`. Without tmux windows pops-up and preview works just fine.

My shell and OS:

```
[I] 11-22 22:36 dpc@futex ~/l/crev (master)> fish --version
fish, version 2.7.1
[I] 11-22 22:36 dpc@futex ~/l/crev (master)> uname -a
Linux futex.dpc.pw 4.14.79 #1-NixOS SMP Sun Nov 4 13:52:51 UTC 2018 x86_64 GNU/Linux
```

**Comment by dpc** [comment] 2018-11-23 06:37
I started `bash` in `tmux` and run `kak`. Same issue.

**Comment by andreyorst** [comment] 2018-11-23 06:55
I' think I know how to fix this. What's your `sh` is pointing to?

**Comment by dpc** [comment] 2018-11-23 06:56
```
[I] 11-22 22:55 dpc@futex ~/l/crev (master)> which sh
/run/current-system/sw/bin/sh
[I] 11-22 22:55 dpc@futex ~/l/crev (master)> ls -alh (which sh)
lrwxrwxrwx 1 root root 75 Dec 31  1969 /run/current-system/sw/bin/sh -> /nix/store/pd3xx55jjik53gvbyrs4h0him03l3wah-bash-interactive-4.4-p23/bin/sh
```

**Comment by andreyorst** [comment] 2018-11-23 07:01
please try with `fix-fish-tmux-preview` branch

**Comment by dpc** [comment] 2018-11-23 08:10
No change.

I really hope I haven't screwed up something, but I checked twice if I'm on the right branch and have that new commit.

**Comment by andreyorst** [comment] 2018-11-23 08:17
hm. Try to export SHELL to bash before launching Kakoune. 
```sh
export SHELL=$(command -v bash); kak
```

**Comment by dpc** [comment] 2018-11-23 08:32
No change.

**Comment by dpc** [comment] 2018-11-23 08:33
I need to go to sleep now. If you can tell me where exactly is the problem, then I should be able to debug myself tomorrow. I know shell scripting quite well, I just don't know `kak`/`fzf.kak` well.

**Comment by andreyorst** [comment] 2018-11-23 08:48
I suppose that the problem here is similar to https://github.com/andreyorst/fzf.kak/issues/15#issuecomment-429299118

Also I've forgotten to escape `$sh` variable, so maybe now it'll be working. I'll investigate it further too.

> I just don't know kak/fzf.kak well.

The shellscript in this version is total mess, I'm refactoring it in `v1.0.0` branch, so maybe you'll should check there. It's similar, but lot cleaner already.

**Comment by andreyorst** [comment] 2018-11-23 09:14
The weird problem is that even if I set fish as my login shell the command isn't breaking for me on master.

**Comment by andreyorst** [comment] 2018-11-23 09:56
@TeddyDD If you're still using fzf.kak, and fish combo, could you please previews it inside tmux?

**Comment by TeddyDD** [comment] 2018-11-23 10:58
I'v got "Illegal command name" error.

**Comment by andreyorst** [comment] 2018-11-23 11:36
@TeddyDD Good that this can be reproduced. What about x11 and `fix-fish-tmux-preview` branch? Sorry to bother you, but I can't reproduce the issue for some reason...

**Comment by andreyorst** [comment] 2018-11-23 15:07
I've managed to repro it too.

**Comment by andreyorst** [comment] 2018-11-23 16:11
These two lines a pretty similar, however the first one is executed inside kakoune, and the second in external terminal. 
```sh
cmd="$preview_pos $items_command | SHELL=$shell fzf-tmux -d $tmux_height $additional_flags > $tmp"
```
```sh
printf "%s\n" "cd $PWD && $preview_pos $items_command | SHELL=$shell fzf $additional_flags > $tmp" > $fzfcmd
cmd="$kak_opt_termcmd 'sh -c $fzfcmd'"
```
The part with `SHELL=$shell` before `fzf`, where `shell=$(command -v sh)`, is working with external terminal, but not working inside Kakoune with `fzf-tmux` script. I don't know how to workaround this actually. Maybe it is impossible. Maybe I'm missing something. I've tried plenty of ways to do it, but seems that fzf always fallbacks to current default shell for some reason, which is fine when you're using (mostly) posix complaint shell like zsh, but not when you're using fish.

**Comment by andreyorst** [comment] 2018-11-23 16:49
hopefully my guess is wrong. Seems like it's `fzf-tmux` fault.
When I do
```sh
SHELL=$(command -v fish) fzf-tmux --preview '(cat {})'
```
I don't get any error since my shell is zsh. But when I do
```sh
SHELL=$(command -v fish) fzf --preview '(cat {})'
```
I get the same error. Therefore I suppose is that `fzf-tmux` script is just ignoring everything outside of it.

**Comment by andreyorst** [comment] 2018-11-23 19:21
I've decided that I'll just make my own Kakoune based solution for creating tmux split. `fzf-tmux` is somewhat too big for what it is doing actually. I hope this will boost time till fzf appears, and will get rid of such awkward situations.

**Comment by andreyorst** [comment] 2018-11-24 09:01
@dpc I've fixed this, but in `v1.0.0` branch, as it was so much easier to do with more clean code. If you can, I'd ask you to wait until refactoring is finished and I'll merge everything to master branch, or use `v1.0.0` branch directly *(although I don't push broken code there I can't be sure that everything is working all the time, so better not update it until necessary)*. Also this will hugely help with testing `v1.0.0`

**Comment by dpc** [comment] 2018-11-24 17:33
@andreyorst It's working on v1.0.0! So pretty... :) colors and everything...

**Comment by andreyorst** [comment] 2018-11-24 18:38
Great. I'll close this once changes will get to master.

**Comment by andreyorst** [comment] 2018-11-25 13:17
Changes are in master

**Closed by andreyorst** 2018-11-25 13:17 UTC
Labels: bug, compatibility

**Comment by dpc** [comment] 2018-11-25 19:40
That was fast!
